Repository abs-tudelft/tydi, pull requests merged in 2020-03, with the labels that each got.

#2 Phase 1: template generation
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
  .gitignore
  Cargo.toml
  LICENSE
  README.md
  src/bin/tydi.rs
  src/design/library.rs
  src/design/mod.rs
  src/design/project.rs
  src/design/streamlet.rs
  src/error.rs
  src/generator/chisel/mod.rs
  src/generator/common.rs
  src/generator/mod.rs
  src/generator/vhdl/impls.rs
  src/generator/vhdl/mod.rs
  src/lib.rs
  src/logical.rs
  src/parser/mod.rs
  src/parser/nom.rs
  src/physical.rs
  src/traits.rs
  src/util.rs
  tests/vhdl.rs
Labels: 🦀 implementation

#31 Have user-friendly part of back-end produce records with names as in examples and spec.
  src/generator/common.rs
  src/generator/mod.rs
  src/generator/vhdl/impls.rs
  src/generator/vhdl/mod.rs
  tests/vhdl.rs
Labels: WIP: do not merge

#47 Update mdbook to 0.3.6
  .github/workflows/book.yml
Labels: dependencies, documentation

#45 Add type safe iterators for splitted logical streams
  src/design/streamlet.rs
  src/generator/common/convert.rs
  src/lib.rs
  src/logical.rs
  src/parser/nom.rs
Labels: 🦀 implementation
