Repository abs-tudelft/tydi, pull requests merged in 2020-02, with the labels that each got.

#10 Add book hierarchy
  book/book.toml
  book/src/README.md
  book/src/SUMMARY.md
  book/src/faq.md
  book/src/introduction/introduction.md
  book/src/references.md
  book/src/specification/README.md
  book/src/specification/logical.md
  book/src/specification/physical.md
  book/src/specification/streamlet.md
  book/src/tools/README.md
  book/src/tools/compositors.md
  book/src/tools/generators.md
  book/src/tydi.md
  book/theme/highlight.js
Labels: documentation

#13 Logical stream specification
  book/src/SUMMARY.md
  book/src/specification/README.md
  book/src/specification/logical.md
  book/src/specification/notation.md
  book/src/specification/physical.md
  book/src/specification/streamlet.md
Labels: 🐬 specification

#16 Fix a typo in logical spec
  book/src/specification/logical.md
Labels: 🐬 specification

#17 Setup cli
  Cargo.toml
  src/main.rs
Labels: 🦀 implementation

#18 Fix a typo in the union example
  book/src/specification/logical.md
Labels: 🐬 specification

#12 Align code with spec
  Cargo.toml
  src/data.rs
  src/error.rs
  src/generator/mod.rs
  src/lib.rs
  src/logical.rs
  src/parser/data.rs
  src/parser/mod.rs
  src/physical.rs
  src/streamlet.rs
  src/traits.rs
  src/util.rs
Labels: 🦀 implementation

#19 Add parser for Streamlet definition files
  Cargo.toml
  src/error.rs
  src/generator/common.rs
  src/lib.rs
  src/library.rs
  src/logical.rs
  src/parser/logical.rs
  src/parser/mod.rs
  src/parser/nom.rs
  src/parser/sdf.pest
  src/parser/streamlet.rs
  src/physical.rs
  src/streamlet.rs
  src/traits.rs
  src/util.rs
Labels: 🦀 implementation
